//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10/20/2014 8:37:40 PM
namespace AppBay.Tests.DataServices
{
    
    /// <summary>
    /// There are no comments for Entities in the schema.
    /// </summary>
    public partial class Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("AppBay.Console.Models", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("AppBay.Tests.DataServices", typeName.Substring(21)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("AppBay.Tests.DataServices", global::System.StringComparison.Ordinal))
            {
                return string.Concat("AppBay.Console.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Jobs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<JobDescription> Jobs
        {
            get
            {
                if ((this._Jobs == null))
                {
                    this._Jobs = base.CreateQuery<JobDescription>("Jobs");
                }
                return this._Jobs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<JobDescription> _Jobs;
        /// <summary>
        /// There are no comments for Packages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Package> Packages
        {
            get
            {
                if ((this._Packages == null))
                {
                    this._Packages = base.CreateQuery<Package>("Packages");
                }
                return this._Packages;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Package> _Packages;
        /// <summary>
        /// There are no comments for JobResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<JobResult> JobResults
        {
            get
            {
                if ((this._JobResults == null))
                {
                    this._JobResults = base.CreateQuery<JobResult>("JobResults");
                }
                return this._JobResults;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<JobResult> _JobResults;
        /// <summary>
        /// There are no comments for Jobs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToJobs(JobDescription jobDescription)
        {
            base.AddObject("Jobs", jobDescription);
        }
        /// <summary>
        /// There are no comments for Packages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPackages(Package package)
        {
            base.AddObject("Packages", package);
        }
        /// <summary>
        /// There are no comments for JobResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToJobResults(JobResult jobResult)
        {
            base.AddObject("JobResults", jobResult);
        }
    }
    /// <summary>
    /// There are no comments for AppBay.Console.Models.JobDescription in the schema.
    /// </summary>
    /// <KeyProperties>
    /// JobId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Jobs")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("JobId")]
    public partial class JobDescription : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new JobDescription object.
        /// </summary>
        /// <param name="jobId">Initial value of JobId.</param>
        /// <param name="packageId">Initial value of PackageId.</param>
        /// <param name="added">Initial value of Added.</param>
        /// <param name="isRunning">Initial value of IsRunning.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static JobDescription CreateJobDescription(int jobId, int packageId, global::System.DateTime added, bool isRunning)
        {
            JobDescription jobDescription = new JobDescription();
            jobDescription.JobId = jobId;
            jobDescription.PackageId = packageId;
            jobDescription.Added = added;
            jobDescription.IsRunning = isRunning;
            return jobDescription;
        }
        /// <summary>
        /// There are no comments for Property JobId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int JobId
        {
            get
            {
                return this._JobId;
            }
            set
            {
                this.OnJobIdChanging(value);
                this._JobId = value;
                this.OnJobIdChanged();
                this.OnPropertyChanged("JobId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _JobId;
        partial void OnJobIdChanging(int value);
        partial void OnJobIdChanged();
        /// <summary>
        /// There are no comments for Property PackageId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PackageId
        {
            get
            {
                return this._PackageId;
            }
            set
            {
                this.OnPackageIdChanging(value);
                this._PackageId = value;
                this.OnPackageIdChanged();
                this.OnPropertyChanged("PackageId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PackageId;
        partial void OnPackageIdChanging(int value);
        partial void OnPackageIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Added in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Added
        {
            get
            {
                return this._Added;
            }
            set
            {
                this.OnAddedChanging(value);
                this._Added = value;
                this.OnAddedChanged();
                this.OnPropertyChanged("Added");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Added;
        partial void OnAddedChanging(global::System.DateTime value);
        partial void OnAddedChanged();
        /// <summary>
        /// There are no comments for Property Started in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Started
        {
            get
            {
                return this._Started;
            }
            set
            {
                this.OnStartedChanging(value);
                this._Started = value;
                this.OnStartedChanged();
                this.OnPropertyChanged("Started");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Started;
        partial void OnStartedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnStartedChanged();
        /// <summary>
        /// There are no comments for Property IsRunning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsRunning
        {
            get
            {
                return this._IsRunning;
            }
            set
            {
                this.OnIsRunningChanging(value);
                this._IsRunning = value;
                this.OnIsRunningChanged();
                this.OnPropertyChanged("IsRunning");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsRunning;
        partial void OnIsRunningChanging(bool value);
        partial void OnIsRunningChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AppBay.Console.Models.Package in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PackageId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Packages")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PackageId")]
    public partial class Package : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Package object.
        /// </summary>
        /// <param name="packageId">Initial value of PackageId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Package CreatePackage(int packageId)
        {
            Package package = new Package();
            package.PackageId = packageId;
            return package;
        }
        /// <summary>
        /// There are no comments for Property PackageId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PackageId
        {
            get
            {
                return this._PackageId;
            }
            set
            {
                this.OnPackageIdChanging(value);
                this._PackageId = value;
                this.OnPackageIdChanged();
                this.OnPropertyChanged("PackageId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PackageId;
        partial void OnPackageIdChanging(int value);
        partial void OnPackageIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property TargetClassName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TargetClassName
        {
            get
            {
                return this._TargetClassName;
            }
            set
            {
                this.OnTargetClassNameChanging(value);
                this._TargetClassName = value;
                this.OnTargetClassNameChanged();
                this.OnPropertyChanged("TargetClassName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TargetClassName;
        partial void OnTargetClassNameChanging(string value);
        partial void OnTargetClassNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AppBay.Console.Models.JobResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// JobResultId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("JobResults")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("JobResultId")]
    public partial class JobResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new JobResult object.
        /// </summary>
        /// <param name="jobResultId">Initial value of JobResultId.</param>
        /// <param name="started">Initial value of Started.</param>
        /// <param name="finished">Initial value of Finished.</param>
        /// <param name="isSuccess">Initial value of IsSuccess.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static JobResult CreateJobResult(int jobResultId, global::System.DateTime started, global::System.DateTime finished, bool isSuccess)
        {
            JobResult jobResult = new JobResult();
            jobResult.JobResultId = jobResultId;
            jobResult.Started = started;
            jobResult.Finished = finished;
            jobResult.IsSuccess = isSuccess;
            return jobResult;
        }
        /// <summary>
        /// There are no comments for Property JobResultId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int JobResultId
        {
            get
            {
                return this._JobResultId;
            }
            set
            {
                this.OnJobResultIdChanging(value);
                this._JobResultId = value;
                this.OnJobResultIdChanged();
                this.OnPropertyChanged("JobResultId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _JobResultId;
        partial void OnJobResultIdChanging(int value);
        partial void OnJobResultIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Started in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Started
        {
            get
            {
                return this._Started;
            }
            set
            {
                this.OnStartedChanging(value);
                this._Started = value;
                this.OnStartedChanged();
                this.OnPropertyChanged("Started");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Started;
        partial void OnStartedChanging(global::System.DateTime value);
        partial void OnStartedChanged();
        /// <summary>
        /// There are no comments for Property Finished in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Finished
        {
            get
            {
                return this._Finished;
            }
            set
            {
                this.OnFinishedChanging(value);
                this._Finished = value;
                this.OnFinishedChanged();
                this.OnPropertyChanged("Finished");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Finished;
        partial void OnFinishedChanging(global::System.DateTime value);
        partial void OnFinishedChanged();
        /// <summary>
        /// There are no comments for Property IsSuccess in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsSuccess
        {
            get
            {
                return this._IsSuccess;
            }
            set
            {
                this.OnIsSuccessChanging(value);
                this._IsSuccess = value;
                this.OnIsSuccessChanged();
                this.OnPropertyChanged("IsSuccess");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsSuccess;
        partial void OnIsSuccessChanging(bool value);
        partial void OnIsSuccessChanged();
        /// <summary>
        /// There are no comments for Property ErrorMessage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ErrorMessage
        {
            get
            {
                return this._ErrorMessage;
            }
            set
            {
                this.OnErrorMessageChanging(value);
                this._ErrorMessage = value;
                this.OnErrorMessageChanged();
                this.OnPropertyChanged("ErrorMessage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ErrorMessage;
        partial void OnErrorMessageChanging(string value);
        partial void OnErrorMessageChanged();
        /// <summary>
        /// There are no comments for Property SerializedResult in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SerializedResult
        {
            get
            {
                return this._SerializedResult;
            }
            set
            {
                this.OnSerializedResultChanging(value);
                this._SerializedResult = value;
                this.OnSerializedResultChanged();
                this.OnPropertyChanged("SerializedResult");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SerializedResult;
        partial void OnSerializedResultChanging(string value);
        partial void OnSerializedResultChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
